name: Distribute executable

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  # Cross-compile
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.16.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: myapp
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

  # tests and Linux build
  distribute:
    needs: xgo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test
        run: go test -v ./...

      - name: Build Linux
        run: go build -o build/renpy-graphviz-linux -v ./...

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GO_RELEASE_KEY }}
